name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: |
        mv LockLogin-API locklogin-API
        mv LockLogin-bundle locklogin-bundle
        mv LockLogin-common locklogin-common
        mv LockLogin-manager locklogin-manager
        mv LockLogin-spigot locklogin-spigot
        mv LockLogin-velocity locklogin-velocity
        mvn -B package --file pom.xml
    - name: Archive results
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: target/install
